---
- hosts: all
  gather_facts: no
  tasks:
    - name: create files
      file:
        path: "~/{{item.name}}"
        state: touch
        mode: "{{item.perm}}"
      with_items:
      - {name: file1, perm: "0777"}
      - {name: file2, perm: "0644"}
