--- # Declare a variable  at play and print the value.
- name: Print a variable from play
  hosts: all
  #vars:
    #URL: play.google.com
  tasks:
  - name: Print a variable
    debug:
      msg: "URL = {{URL}}"
