--- # Access varibles from facts.
    - name: Access facts.
      hosts: all
      tasks:
      - name: Print OS Family of node.
        debug:
          msg: OS Family is = {{ansible_os_family}}
      - name: Print OS Architecture of node.
        debug:
          msg: Architecture is = {{ansible_architecture}}
      - name: Print OS Distribution of node.
        debug:
          msg: Distribution is = {{ansible_distribution}}
