--- # Install Apache Service
- hosts: webserver
  become: true
  tasks:
  - name: Install httpd Package
    yum: 
      name: httpd
      state: present
  - name: Starting httpd Service
    service:
      name: httpd
      state: started
      enabled: true
  - raw: "echo '<h2> Welcome to Rise 'n' Shine </h2>' | sudo tee /var/www/html/index.html"

