--- # Install http server and Deploy the Html File
-  hosts: web
   remote_user: devops
   become: yes
   tasks:
      - name: Install Apache Server
        yum:
            name: httpd
            state: present
        notify:
          - startservice
      - name: create a file if does not exist
        file:
            state: touch
            path: /var/www/html/hostname.html
      - name: Adding line
        lineinfile:
             state: present
             path: /var/www/html/hostname.html
             line: Hostname= {{ansible_distribution}}
        notify:
          - startservice
   handlers:
      - name: startservice
        service:
          name: httpd
          state: restarted
          enabled: true

