- name: Demo on tags
  hosts: all
  tasks:
  - name: Print on Ubuntu Tag
    debug:
      msg: Ubuntu1
    tags:
      - ubuntu

  - name: Print on Ubuntu Tag
    debug:
      msg: Ubuntu2
    tags:
      - ubuntu
  
  - name: Print on CentOS tag
    debug:
      msg: "CentOS Task 1"
    tags:
      - centos

  - name: Print on CentOS tag
    debug:
      msg: "CentOS Task 2"
    tags:
      - centos
