### Declare a variable at task and print the value.

- name: Print a variable from task
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a variable
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.google.com
