---
- hosts: app
  become: true
  roles:
    - role: java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

- hosts: web
  become: true
  roles:
    - role: apache
